In [1]:
import numpy as np
import cv2
from tensorflow.keras.models import model_from_json,load_model

2023-01-15 17:13:44.742119: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-15 17:13:44.871511: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-15 17:13:44.874438: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/pradeep/anaconda3/envs/nlpenv/lib/python3.9/site-packages/cv2/../../lib64:
20

In [7]:
# load the cascade
# cascadeClassifier is the face classification model
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [8]:
# capture video from webcam
# cap = cv2.VideoCapture(0)
cap = cv2.VideoCapture('/home/pradeep/mySpace/DAI/projects/music-recommendation-using-face-emotion/data/expressions.mp4')
# to use video file as input
# cap = cv2.VideoCapture('filename.mp4')

In [9]:
from deepface import DeepFace

In [10]:
import copy

while True:
    # Read the frame/image from the video
    ret, frame = cap.read()
    print(frame)
    img = copy.deepcopy(frame)
    # img = cv2.resize(img,(600,500))
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x,y,w,h) in faces:
        fc = gray[y:y+h, x:x+w]
        
        roi = cv2.resize(fc, (48,48))

        result = DeepFace.analyze(img,actions = ['emotion'],enforce_detection=False)
        
        text = result['dominant_emotion']
        cv2.putText(img, text, (x, y-5),
        cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 0, 255), 2)
        img = cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,255), 2)
            
    
    cv2.imshow("frame", img)
    key = cv2.waitKey(1) & 0xff
    if key == 27:
        break
    
cap.release()
cv2.destroyAllWindows()

[[[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 71  89  83]
  [ 72  87  82]
  [ 69  85  80]]

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 72  87  82]
  [ 73  85  81]
  [ 71  84  80]]

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 71  84  80]
  [ 71  84  80]
  [ 71  84  80]]

 ...

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 83  85  85]
  [ 84  87  86]
  [ 85  88  87]]

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 82  84  84]
  [ 82  84  84]
  [ 84  87  86]]

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 83  83  83]
  [ 84  83  85]
  [ 85  84  87]]]
[[[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 77  86  78]
  [ 75  86  75]
  [ 74  85  74]]

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 75  84  78]
  [ 75  85  77]
  [ 74  84  76]]

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 73  82  76]
  [ 73  82  76]
  [ 73  82  76]]

 ...

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ..

2023-01-15 17:11:14.125929: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/pradeep/anaconda3/envs/nlpenv/lib/python3.9/site-packages/cv2/../../lib64:
2023-01-15 17:11:14.126156: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-01-15 17:11:14.126180: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (pradeep-Vostro-5402): /proc/driver/nvidia/version does not exist
2023-01-15 17:11:14.127081: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, r

1/1 [==============================] - 0s 164ms/step
[[[177 156 151]
  [180 159 153]
  [183 162 157]
  ...
  [ 90  75  98]
  [ 84  80  92]
  [ 84  80  92]]

 [[177 156 152]
  [178 157 154]
  [182 161 155]
  ...
  [ 91  78  96]
  [ 84  80  92]
  [ 83  79  91]]

 [[175 153 152]
  [177 155 154]
  [180 157 156]
  ...
  [ 89  80  93]
  [ 87  81  93]
  [ 85  78  91]]

 ...

 [[206 233 247]
  [200 227 241]
  [196 224 237]
  ...
  [ 82  91  90]
  [ 82  92  88]
  [ 82  92  88]]

 [[205 232 246]
  [192 219 233]
  [192 221 237]
  ...
  [ 83  92  91]
  [ 83  92  91]
  [ 83  92  91]]

 [[200 227 241]
  [195 222 236]
  [194 220 237]
  ...
  [ 83  92  91]
  [ 84  94  92]
  [ 85  95  93]]]
1/1 [==============================] - 0s 14ms/step
[[[188 172 167]
  [183 166 162]
  [183 165 163]
  ...
  [ 85  93 103]
  [ 71  79  89]
  [ 75  83  93]]

 [[188 172 170]
  [182 167 164]
  [177 162 160]
  ...
  [ 78  84  94]
  [ 75  84  91]
  [ 74  83  90]]

 [[190 173 169]
  [190 173 169]
  [186 168 167]
  ...
  [